version: "3.9"
services:
  api:
    build:
      context: ..
      dockerfile: infra/Dockerfile.api
    restart: unless-stopped
    container_name: MedAI
    env_file:
      - ./../infra/.env
    networks:
      - shared_net

networks:
  shared_net:
    external: true